### ISSUE TITLE
error installing module

### ISSUE THREAD

**Issue by sponnet** [panosoft/node-chartist#3]
Module installation fails here because  he can't find the file 'node_modules/chartist/dist/chartist.min.css'

npm -v = 3.5.2
node -v = v0.12.7

npm install --save node-chartist

> node-chartist@0.2.4 postinstall /Users/sponnet/Documents/projects/babuzo/scripts/node_modules/node-chartist
> npm run build && touch node_modules/canvas.js

> node-chartist@0.2.4 prebuild /Users/sponnet/Documents/projects/babuzo/scripts/node_modules/node-chartist
> rimraf dist/*

> node-chartist@0.2.4 build /Users/sponnet/Documents/projects/babuzo/scripts/node_modules/node-chartist
> lessc lib/main.less dist/main.css
FileError: 'node_modules/chartist/dist/chartist.min.css' wasn't found. Tried - /Users/sponnet/Documents/projects/babuzo/scripts/node_modules/node-chartist/lib/node_modules/chartist/dist/chartist.min.css,/Users/sponnet/Documents/projects/babuzo/scripts/node_modules/node-chartist/lib/node_modules/chartist/dist/chartist.min.css,node_modules/chartist/dist/chartist.min.css in /Users/sponnet/Documents/projects/babuzo/scripts/node_modules/node-chartist/lib/main.less on line 1, column 1:
1 @import (less) 'node_modules/chartist/dist/chartist.min.css';
2

**Comment by alexgig** [comment]
Thanks @sponnet.

Without an api within `chartist` itself to return the location of it's css file, certain assumptions must be made about the post install directory structure.

The node_modules directory structure underwent a breaking change from npm v2 -> v3 which is the root cause of this issue.

We are currently supporting the LTS version of node (v4) and the version of npm packaged with it (v2). Our plan is to update the build scripts as new LTS versions are released.

Best regards,
Alex

**Comment by sponnet** [comment]
Thanks for the follow up Alex!

**Comment by alexgig** [comment]
You're very welcome @sponnet. Have a great day!

**Comment by alexgig** [comment]
Hello @sponnet ,

Just wanted to let you know that `+ node-chartist@0.2.8` is now npm 3 compatible.

Best,
Alex
