### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by MichaelJC91** [panosoft/node-chartist#9]
How do I make the charts responsive with this library?

**Comment by alexgig** [comment]
Hello @MichaelJC91,

Since this library renders charts on the server and not within a browser window, the concept of "responsive" doesn't really make sense. This library just returns a chart svg of the specified size at render time.

That said, the best you can do on the server side is call `generate` with appropriate `width` and `height` options.

If you need something truly responsive, then I'd recommend running [Chartist.js](https://gionkunz.github.io/chartist-js/index.html) on the front-end. 

Hope that helps.

Best regards,
Alex
